/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    stories: Story;
    characters: Character;
    themes: Theme;
    plots: Plot;
    styles: Style;
  };
  globals: {};
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Story {
  id: string;
  title: string;
  character: string | Character;
  theme: string | Theme;
  plot: string | Plot;
  style: string | Style;
  prompt?: string;
  status?: 'new' | 'awaiting' | 'unapproved' | 'approved';
  content?: string;
  createdAt: string;
  updatedAt: string;
}
export interface Character {
  id: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
export interface Theme {
  id: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
export interface Plot {
  id: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
export interface Style {
  id: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
